---
- name: Copy and build Redis config
  template:
    src: redis.conf.j2
    dest: /etc/redis/{{ item.port }}.conf
  with_items: "{{ redis_cluster_instances }}"
  notify: restart redis

- name: Copy and parse redis systemd unit file
  template:
    src: redis-server.service.j2
    dest: /lib/systemd/system/redis-server@.service
    mode: 0644
  with_items: "{{ redis_cluster_instances }}"
  notify: restart redis

- name: Get pid of default redis on localhost 6379
  shell: netstat -nltp | grep 127.0.0.1:6379 | awk '{print $7}' | cut -d '/' -f1
  register: default_redis_pid_on_localhost6379

- name: Kill default redis on localhost 6379
  shell: kill -9 {{ default_redis_pid_on_localhost6379.stdout }}
  when: default_redis_pid_on_localhost6379.stdout != ''

- name: Ensure redis-server service is up
  systemd:
    name: "redis-server@{{ item.port }}"
    enabled: yes
    state: started
    daemon_reload: yes
  with_items: "{{ redis_cluster_instances }}"

# # This can not effectively shutdown 127.0.0.1:6379 redis (default redis service?)
# - name: Ensure default redis service is down
#   systemd:
#     name: redis_6379
#     enabled: no
#     state: stopped
#     daemon_reload: yes
